---
- name: Restart teamspeak services
  become: false
  ansible.builtin.systemd:
    name: teamspeak.service
    state: restarted
    daemon_reload: true
    scope: user
  listen: "restart teamspeak services"
