---
teamspeak_repository: https://files.teamspeak-services.com/releases
teamspeak_version: 3.13.7
teamspeak_arch: amd64
teamspeak_client: false
teamspeak_server: true
teamspeak_dir: /var/lib/teamspeak

# Server specific settings
teamspeak_user: teamspeak
teamspeak_group: "{{ teamspeak_user }}"
