---
- name: Install
  ansible.builtin.import_tasks: install.yaml
  become: true
  tags:
    - teamspeak
    - teamspeak_install

- name: Configure
  ansible.builtin.import_tasks: configure.yaml
  tags:
    - teamspeak
    - teamspeak_configure
